### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by misaka-eth** [alexeyden/openess#1]
```
root@test:~/openess# make dist
go build -o openess cmd/openess/*.go
malformed import path "cmd/openess/*.go": invalid char '*'
make: *** [Makefile:11: openess] Error 1
```

```
root@test:~/openess# go build
no Go files in /root/openess
```

Can you provide detailed instruction on how to build this project? (I'm not familiar with go)

**Comment by alexeyden** [comment]
Looks like I forgot to commit some files, sorry
Will try to fix that in a couple of days

**Comment by alexeyden** [comment]
Fixed. If you're building on the target machine,  `make` should do it. Then you can either proceed with installation (`data/install.sh`) or simply run `./openess -b` in place

**Comment by misaka-eth** [comment]
Thanks, I'll test in two week when my inverter get installed
